keys:
  - &oxyhome age1ayscr4gjzf5gyez5khvygakfjt3yyxlv6vuwjc275hpe2kmslarsykqrs8
creation_rules:
  - path_regex: secrets/[^/]+(\.(yaml|json|env|ini|conf))?$
    key_groups:
      - age:
          - *oxyhome
