keys:
  - &svr1 age13cu9qf58vw7wkjkd3lrwrqythrylzh02w0kgsj6ly3m9gcj67vzqznw875
creation_rules:
  - path_regex: secrets/[^/]+(\.(yaml|json|env|ini|conf))?$
    key_groups:
      - age:
          - *svr1
