keys:
  - &svr1 age105nlwxh5hpdwxgnsms8q7nu3nd0vu4jx07tg6ehuryzasetlrpdq6ah3zd
creation_rules:
  - path_regex: secrets/[^/]+(\.(yaml|json|env|ini|conf))?$
    key_groups:
      - age:
          - *svr1
