# Define packages by type
casks = [
    # Utilities
    'aldente',
    'raycast',
    'bartender',
    'the-unarchiver',
    # 'sentinel',
    'betterdisplay',
    'shottr',
    'cleanmymac',
    'rectangle-pro',
    'balenaetcher',
    'music-decoy',
    'prefs-editor',
    'logi-options+'

    # CLI Tools
    'warp',

    # Security & Privacy
    '1password',
    '1password-cli',
    'yubico-authenticator',

    # Browsers
    'arc',
    'zen-browser',

    # Development
    'visual-studio-code',
    'jetbrains-toolbox',
    'cursor',
    'zed',
    'orbstack',
    'expo-orbit',
    'postman',

    # Network
    'lulu',
    'tailscale',

    # Design
    'figma',

    # Database
    'dataflare',

    # Media
    'iina',
    'spotify',

    # Cloud Storage
    'nextcloud',

    # Remote Access
    'rustdesk',
    'anydesk',

    # File Transfer
    'free-download-manager',

    # Social & Communication
    'discord',
    'telegram',
    'microsoft-teams',

    # Virtualization
    'crossover',
    'whisky',
    'vmware-fusion',
    'virtualbuddy',

    # Productivity
    'notion'

    # Gaming
    'steam',
    'epic-games',
    'nvidia-geforce-now',
    
]

brews = [
    # CLI Tools
    'gh',
    'bat',
    'eza',
    'fnm',
    'fish',
    'fastfetch',
    'mas'
]

mas = [
    # Mac App Store apps
    { name: 'Clamshell', id: 6477896729 },
    { name: '1Password for Safari', id: 1569813296 },
    { name: 'Xcode', id: 497799835 }
]

# Install packages
casks.each { |app| cask app }
brews.each { |app| brew app }
mas.each { |app| mas app[:name], id: app[:id] }