---
app_layout:
  - - folder_layout:
        - - Arc
          - Brave Browser
          - Safari
          - Zen Browser
      folder_title: Browsers
    - folder_layout:
        - - Android Studio
          - Cursor
          - Dataflare
          - Expo Orbit
          - IntelliJ IDEA Community Edition
          - JetBrains Toolbox
          - OrbStack
          - PyCharm Community Edition
          - Visual Studio Code
          - Warp
          - Zed
      folder_title: Development
    - folder_layout:
        - - Figma
          - Freeform
      folder_title: Design
    - folder_layout:
        - - Free Download Manager
          - Nextcloud
          # - Nicotine+
      folder_title: File Sharing
    - folder_layout:
        - - Epic Games Launcher
          - NVIDIA GeForce NOW
          - Steam
          - Whisky
      folder_title: Games
    - folder_layout:
        - - Spotify
          - VLC
      folder_title: Media
    - folder_layout:
        - - Activity Monitor
          - AirPort Utility
          - Bluetooth File Exchange
          - ColorSync Utility
          - Digital Color Meter
          - Disk Utility
          - Find My
          - LogiPluginService
          - Maps
          - Photos
          - Shortcuts
      folder_title: Other
    - folder_layout:
        - - 1Password
          - 1Password for Safari
          - LuLu
          - Passwords
          - Sentinel
          - Tailscale
          - Yubico Authenticator
      folder_title: Security & Privacy
    - folder_layout:
        - - Lunatask
          - Microsoft Teams
          - Notion
          - Telegram
      folder_title: Social
    - folder_layout:
        - - AlDente
          - AnyDesk
          - balenaEtcher
          - Bartender 5
          - BetterDisplay
          - Clamshell
          - CleanMyMac
          - Logi Options+
          - Raycast
          - Rectangle Pro
          - Shottr
          - The Unarchiver
      folder_title: Utilities
    - folder_layout:
        - - CrossOver
          - Parallels Desktop
          - Parallels Desktop Activation Tool SIP ON
          - Parallels Toolbox
          - RustDesk
          - VMware Fusion
      folder_title: VM & Remote
hidden_apps:
  - App Store
  - Audio MIDI Setup
  - Automator
  - Books
  - Calculator
  - Calendar
  - Chess
  - Clock
  - Console
  - Contacts
  - Dictionary
  - FaceTime
  - Font Book
  - Grapher
  - Home
  - Image Capture
  - iPhone Mirroring
  - Mail
  - Messages
  - Migration Assistant
  - Mission Control
  - Music
  - Notes
  - Photo Booth
  - Podcasts
  - Preview
  - Print Center
  - QuickTime Player
  - Reminders
  - Screen Sharing
  - Screenshot
  - Script Editor
  - Siri
  - Stickies
  - Stocks
  - System Information
  - System Settings
  - TV
  - Terminal
  - TextEdit
  - Time Machine
  - Tips
  - Voice Memos
  - VoiceOver Utility
  - Weather
