name: "Release Custom NixOS ISO"

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture:
          - x86_64-linux
          - aarch64-linux

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v27

      - name: Build ISO (x86_64)
        if: matrix.architecture == 'x86_64-linux'
        run: |
          nix_bin=$(which nix)
          sudo $nix_bin build .#nixosConfigurations.iso1-x86_64.config.system.build.isoImage

      - name: Build ISO (ARM)
        if: matrix.architecture == 'aarch64-linux'
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: raspios_lite_arm64:latest
          commands: |
            nix_bin=$(which nix)
            $nix_bin build .#nixosConfigurations.iso1-arm.config.system.build.isoImage

      - name: Rename ISO
        run: |
          if [ "${{ matrix.architecture }}" == "x86_64-linux" ]; then
            sudo mv result/iso/nixos-*.iso nixos-x86_64.iso
          else
            sudo mv result/iso/nixos-*.iso nixos-arm.iso
          fi

      - name: Create Tag (if manual run)
        if: github.event_name == 'workflow_dispatch'
        run: |
          tag="v$(date +'%Y.%m.%d.%H.%M')"
          echo "TAG=$tag" >> $GITHUB_ENV
          git tag $tag
          git push origin $tag

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: nixos-${{ matrix.architecture }}.iso
          path: nixos-${{ matrix.architecture }}.iso

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files: nixos-${{ matrix.architecture }}.iso
