name: "Release Custom NixOS ISO"

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - config_name: iso1-x86_64
            architecture: x86_64-linux
          - config_name: iso1-arm
            architecture: aarch64-linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v27

      - name: Build ISO
        run: |
          nix_bin=$(which nix)
          sudo $nix_bin build .#nixosConfigurations.${{ matrix.config_name }}.config.system.build.isoImage

      - name: Rename ISO
        run: sudo mv result/iso/nixos-*.iso nixos-${{ matrix.architecture }}.iso

      - name: Create Tag (if manual run)
        if: github.event_name == 'workflow_dispatch'
        run: |
          tag="v$(date +'%Y.%m.%d.%H.%M')"
          echo "TAG=$tag" >> $GITHUB_ENV
          git tag $tag
          git push origin $tag

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: nixos-${{ matrix.architecture }}.iso
          path: nixos-${{ matrix.architecture }}.iso

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files: nixos-${{ matrix.architecture }}.iso
