name: "Release Custom NixOS ISO"

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        architecture: [x86_64-linux, aarch64-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            extra-platforms = aarch64-linux

      - name: Set up QEMU for ARM builds
        if: matrix.architecture == 'aarch64-linux'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq qemu binfmt-support qemu-user-static

      - name: Build
        run: |
          nix build .#nixosConfigurations.iso1-${{ matrix.architecture }}.config.system.build.isoImage

      - name: Rename
        run: |
          sudo mv result/iso/nixos-*.iso nixos-${{ matrix.architecture }}.iso

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: nixos-${{ matrix.architecture }}.iso
          path: nixos-${{ matrix.architecture }}.iso

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download x86_64 Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nixos-x86_64-linux.iso
          path: .

      - name: Download ARM Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nixos-aarch64-linux.iso
          path: .

      - name: Create Tag (if manual run)
        if: github.event_name == 'workflow_dispatch'
        run: |
          tag="v$(date +'%Y.%m.%d.%H.%M')"
          echo "TAG=$tag" >> $GITHUB_ENV
          git tag $tag
          git push origin $tag

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files: |
            nixos-x86_64-linux.iso
            nixos-aarch64-linux.iso
