---
name: "Release custom NixOS ISO"

on:
  push:
    tags:
      - v*
  workflow_dispatch: null

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v27

      - name: Build ISO
        run: |
          nix_bin=$(which nix)
          sudo $nix_bin build .#nixosConfigurations.iso1.config.system.build.isoImage

      - name: Rename ISO
        run: sudo mv result/iso/nixos-*.iso nixos.iso

      - name: Create Tag (if manual run)
        if: github.event_name == 'workflow_dispatch'
        run: |
          tag="v$(date +'%Y.%m.%d.%H.%M')"
          git tag $tag
          git push origin $tag

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: nixos.iso
          path: nixos.iso

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: $tag
          files: nixos.iso
