---
name: "Release custom NixOS ISO"

on:
  push:
    tags:
      - v*
  workflow_dispatch: null

jobs:
  # This job is responsible for creating the tag if the workflow is run manually
  create_tag:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create and Push Tag
        run: |
          tag="v$(date +'%Y.%m.%d.%H.%M')"
          git tag $tag
          git push origin $tag

      - name: Output Tag Name
        id: vars
        run: echo "TAG=$tag" >> $GITHUB_ENV

  # This job builds the ISO
  build:
    runs-on: ubuntu-latest
    needs: create_tag # Ensure the tag creation job runs first if triggered manually
    steps:
      - name: Checkout Tag
        uses: actions/checkout@v4
        with:
          ref: ${{ env.TAG }} # Checkout the newly created tag

      - uses: cachix/install-nix-action@v27

      - name: Build ISO
        run: |
          nix_bin=$(which nix)
          sudo $nix_bin build .#nixosConfigurations.iso1.config.system.build.isoImage

      - name: Rename ISO
        run: sudo mv result/iso/nixos-*.iso nixos.iso

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: nixos.iso
          path: nixos.iso

  # This job handles the release once the tag is created
  release:
    runs-on: ubuntu-latest
    needs: build # Ensure the build is completed before attempting the release
    steps:
      - name: Checkout Tag
        uses: actions/checkout@v4
        with:
          ref: ${{ env.TAG }} # Checkout the tag again to ensure the release matches

      - name: Download ISO
        uses: actions/download-artifact@v4
        with:
          name: nixos.iso

      - name: Release ISO
        uses: softprops/action-gh-release@v2
        with:
          files: nixos.iso
