name: NixOS Pre-install Script Test
on: [push]
jobs:
  Explore-NixOS:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔍 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check if Linux is detected
        run: |
          if [ "$(uname)" == "Linux" ]; then
            echo "Linux detected"
          fi
      - run: script path/to/pre-install.sh
      - run: echo "🍏 This job's status is ${{ job.status }}."
